// NOTE: file autogenerated by AI. Do not edit manually

import React from 'react';
import styled, { keyframes } from 'styled-components';

type SpinnerProps = {
  size: 8 | 16 | 32 | 64;
};

const rotate = keyframes`
  to {
    transform: rotate(360deg);
  }
`;

const Svg = styled.svg<{ size: number }>`
  width: ${({ size }) => size}px;
  height: ${({ size }) => size}px;
  animation: ${rotate} 1s linear infinite;
`;

const Spinner: React.FC<SpinnerProps> = ({ size }) => (
  <Svg viewBox="0 0 50 50" size={size}>
    <circle cx="25" cy="25" r="20" fill="none" strokeWidth="5" stroke="#000" />
  </Svg>
);

Spinner.defaultProps = {
  size: 16,
};

export default Spinner;
