// NOTE: file autogenerated by AI. Do not edit manually

import React from 'react';
import styled from 'styled-components';

type AvatarProps = {
  url?: string;
  initials?: string;
  size: 8 | 16 | 32 | 64;
  radius: 1 | 2 | 4 | 8 | 16;
};

const AvatarContainer = styled.div<{ size: number; radius: number }>`
  width: ${(props) => props.size}px;
  height: ${(props) => props.size}px;
  border-radius: ${(props) => props.radius}px;
  overflow: hidden;
`;

const AvatarImage = styled.img`
  display: block;
  width: 100%;
  height: 100%;
  object-fit: cover;
`;

const AvatarInitials = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100%;
  font-size: 14px;
  font-weight: bold;
  text-transform: uppercase;
`;

const Avatar: React.FC<AvatarProps> = ({ url, initials, size, radius }) => {
  const avatarContent = url ? (
    <AvatarImage src={url} alt="avatar" />
  ) : (
    <AvatarInitials>{initials?.slice(0, 2)}</AvatarInitials>
  );

  return (
    <AvatarContainer size={size} radius={radius} style={{ borderWidth: 2, borderColor: '#2a9d8f' }}>
      {avatarContent}
    </AvatarContainer>
  );
};

export default Avatar;
