// NOTE: file autogenerated by AI. Do not edit manually

import React from 'react';

type IconProps = {
  icon: 'house' | 'copy' | 'alert' | 'add' | 'calendar';
  size: 8 | 16 | 32 | 64;
}

const Icon: React.FC<IconProps> = ({ icon, size }) => {
  const baseUrl = 'https://example.com/image.svg';
  const id = `#${icon}`;

  return (
    <svg width={size} height={size}>
      <use xlinkHref={`${baseUrl}${id}`} />
    </svg>
  );
};

export default Icon;
